# Generated by Django 6.0 on 2025-12-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchase",
            options={
                "ordering": ["-created"],
                "verbose_name": "compra",
                "verbose_name_plural": "compras",
            },
        ),
        migrations.AlterModelOptions(
            name="sale",
            options={
                "ordering": ["-created"],
                "verbose_name": "venda",
                "verbose_name_plural": "vendas",
            },
        ),
    ]
