# Generated by Django 6.0 on 2025-12-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0002_alter_purchase_options_alter_sale_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseitem",
            name="amount",
            field=models.DecimalField(
                decimal_places=4, default=1, max_digits=6, verbose_name="quantidade"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="preço"
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="amount",
            field=models.DecimalField(
                decimal_places=4, default=1, max_digits=6, verbose_name="quantidade"
            ),
        ),
    ]
