# Generated by Django 6.0 on 2025-12-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commercial",
            "0003_alter_purchaseitem_amount_alter_purchaseitem_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseitem",
            name="amount",
            field=models.DecimalField(
                decimal_places=4, default=1, max_digits=8, verbose_name="quantidade"
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="amount",
            field=models.DecimalField(
                decimal_places=4, default=1, max_digits=8, verbose_name="quantidade"
            ),
        ),
    ]
