# Generated by Django 6.0 on 2025-12-28 05:41

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CashFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "description",
                    models.CharField(max_length=64, verbose_name="descrição"),
                ),
                ("input", models.BooleanField(default=True, verbose_name="entrada")),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="total"
                    ),
                ),
            ],
            options={
                "verbose_name": "fluxo de caixa",
                "verbose_name_plural": "fluxos de caixa",
            },
        ),
    ]
