# Generated by Django 6.0 on 2025-12-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finnancial", "0002_paymentmethod_payment_cashflow_payment_methods"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cashflow",
            options={
                "ordering": ["-created"],
                "verbose_name": "fluxo de caixa",
                "verbose_name_plural": "fluxos de caixa",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "ordering": ["name"],
                "verbose_name": "método de pagamento",
                "verbose_name_plural": "métodos de pagamento",
            },
        ),
    ]
