# Generated by Django 6.0 on 2025-12-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finnancial", "0003_alter_cashflow_options_alter_paymentmethod_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflow",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="total"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=8, verbose_name="valor"
            ),
        ),
    ]
