# Generated by Django 6.0 on 2025-12-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business_partners", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["name"],
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "ordering": ["name"],
                "verbose_name": "fornecedor",
                "verbose_name_plural": "fornecedores",
            },
        ),
    ]
