# Generated by Django 6.0 on 2025-12-28 15:25

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business_partners", "0002_alter_client_options_alter_supplier_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="número de telefone",
            ),
        ),
    ]
