# Generated by Django 6.0 on 2025-12-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_partners", "0003_client_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="house_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
