# Generated by Django 6.0 on 2025-12-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_partners", "0004_client_house_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="house_number",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="número da casa"
            ),
        ),
    ]
