# Generated by Django 6.0 on 2025-12-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockitem",
            name="amount",
            field=models.PositiveIntegerField(default=1, verbose_name="quantidade"),
        ),
    ]
