# Generated by Django 6.0 on 2025-12-28 05:41

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Input",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "measurement",
                    models.CharField(
                        choices=[("UN", "unidade"), ("G", "grama"), ("L", "litro")],
                        default="UN",
                        max_length=2,
                        verbose_name="unidade de medida",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="nome")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, max_digits=6, verbose_name="quantidade"
                    ),
                ),
            ],
            options={
                "verbose_name": "insumo",
                "verbose_name_plural": "insumos",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "measurement",
                    models.CharField(
                        choices=[("UN", "unidade"), ("G", "grama"), ("L", "litro")],
                        default="UN",
                        max_length=2,
                        verbose_name="unidade de medida",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="nome")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="preço"
                    ),
                ),
            ],
            options={
                "verbose_name": "produto",
                "verbose_name_plural": "produtos",
            },
        ),
        migrations.CreateModel(
            name="Packet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=64, verbose_name="nome")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, max_digits=6, verbose_name="quantidade"
                    ),
                ),
                (
                    "input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.input",
                        verbose_name="insumo",
                    ),
                ),
            ],
            options={
                "verbose_name": "pacote",
                "verbose_name_plural": "pacotes",
            },
        ),
        migrations.CreateModel(
            name="ProductInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, max_digits=6, verbose_name="quantidade"
                    ),
                ),
                (
                    "input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.input",
                        verbose_name="insumo",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inputs",
                        to="catalog.product",
                        verbose_name="produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "insumo do produto",
                "verbose_name_plural": "insumos do produto",
                "unique_together": {("product", "input")},
            },
        ),
    ]
