# Generated by Django 6.0 on 2025-12-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="input",
            options={
                "ordering": ["name"],
                "verbose_name": "insumo",
                "verbose_name_plural": "insumos",
            },
        ),
        migrations.AlterModelOptions(
            name="packet",
            options={
                "ordering": ["name"],
                "verbose_name": "pacote",
                "verbose_name_plural": "pacotes",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "produto",
                "verbose_name_plural": "produtos",
            },
        ),
    ]
