# Generated by Django 6.0 on 2025-12-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_input_amount_alter_packet_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="input",
            name="amount",
            field=models.DecimalField(
                decimal_places=4, default=1, max_digits=8, verbose_name="quantidade"
            ),
        ),
        migrations.AlterField(
            model_name="input",
            name="measurement",
            field=models.CharField(
                choices=[
                    ("UN", "unidade"),
                    ("KG", "quilograma"),
                    ("G", "grama"),
                    ("L", "litro"),
                ],
                default="UN",
                max_length=2,
                verbose_name="unidade de medida",
            ),
        ),
        migrations.AlterField(
            model_name="packet",
            name="amount",
            field=models.DecimalField(
                decimal_places=4, default=1, max_digits=8, verbose_name="quantidade"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="measurement",
            field=models.CharField(
                choices=[
                    ("UN", "unidade"),
                    ("KG", "quilograma"),
                    ("G", "grama"),
                    ("L", "litro"),
                ],
                default="UN",
                max_length=2,
                verbose_name="unidade de medida",
            ),
        ),
        migrations.AlterField(
            model_name="productinput",
            name="amount",
            field=models.DecimalField(
                decimal_places=4, default=1, max_digits=8, verbose_name="quantidade"
            ),
        ),
    ]
